version: '2'
services:
  app:
    build: .
    image: google_analytics
    
    tty: true
    ports:
      - '8800:8000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin1:admin1@postgres:5432/test_db
      
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin1
      POSTGRES_USER: admin1
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'