version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test_db
    ports:
      - '8600:8000'
      
  app:
    build: .
    image: google_analytics
    
    tty: true
    ports:
      - '8800:8000'
    depends_on:
      - postgres